version: '3'
services:
  app:
    build:
      context: ./
      target: dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    ports:
      - "80:80"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
    networks:
      - laravel
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "dg"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "multi_food_db"
      # MYSQL_PORT: 3306
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # image: mariadb:latest
    # container_name: mariadb
    # environment:
    #   MYSQL_ROOT_PASSWORD: "secret"
    #   # MYSQL_USER: "dg"
    #   # MYSQL_PASSWORD: "root"
    #   MYSQL_DATABASE: "multi_food_db"
    ports:
      - 33061:3306
    volumes:
      - 'mysql8:/var/lib/mysql'
      - './installation/database.sql:/docker-entrypoint-initdb.d/01init.sql'
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST : "db"
      MYSQL_USERNAME: "dg"
      MYSQL_ROOT_PASSWORD: "root"
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - laravel
    # volumes:
    #   - ./docker/phpmyadmin
networks:
  laravel:
    driver: bridge
volumes:
  mysql8:
    driver: local
